if [ -f "$HOME/.zsh.local" ]; then source "$HOME/.zsh.local"; fi

echo "Activating zsh plugins..."
for p in $HOME/.zsh/plugins/*; do
  local plugin="${p##*/}"
  for initscript in ${plugin}.zsh ${plugin}.plugin.zsh ${plugin}.sh; do
    if [ -f $p/$initscript ]; then
      echo "-> $plugin"
      source $p/$initscript
      break
    fi
  done
done

if ls --block-size=1K &>/dev/null; then
  # GNU
  alias ls='ls --color=auto'
else
  # BSD
  export CLICOLOR=true
fi

bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

export HISTFILE=~/.zsh_history
export HISTSIZE=10000000
export SAVEHIST=10000000
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_VERIFY

#eval $(ssh-agent)
